---
- name: Create a Tomcat User
  user:
    name: tomcat

- name: Create a Tomcat Group
  group:
    name: tomcat

- name: Install JAVA SDK and PolicyKit
  package:
    name: "{{ item }}"
    state: present
  with_items: 
    - polkit
    - java-17-openjdk

- name: Create a Tomcat Directory
  file:
    path: /opt/tomcat9
    owner: tomcat
    group: tomcat
    mode: 755
    recurse: yes

- name: Download & unarchive Tomcat
  unarchive:
    src: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.64/bin/apache-tomcat-9.0.64.tar.gz
    dest: /opt/tomcat9
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Change ownership of tomcat directory
  file:
    path: /opt/tomcat9
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory

- name: Copy Tomcat service from local to remote
  copy:
    src: "files/tomcat.service"
    dest: /etc/systemd/system/
    mode: 0755
 
- name: Enable Tomcat
  service:
    daemon_reload: yes
    name: tomcat
    state: restarted
    enabled: yes

- name: collect facts about system services
  service_facts:
  
- name: Print tomcat service facts 
  ansible.builtin.debug:
    var: ansible_facts.services['tomcat.service']
  failed_when: ansible_facts.services['tomcat.service'].state != "running"
